[2023-09-06 02:40:12] [INFO] >>>  SQLÖ´ĞĞ³É¹¦: test_temp_aa
[2023-09-06 02:40:12] [ERROR] >>>  Job "execute_sql (trigger: cron[hour='2', minute='40', second='0'], next run at: 2023-09-07 02:40:00 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\offline_task\data_sync.py", line 426, in execute_sql
    execute_dependency_jobs(default_engine)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\dags\dags_task.py", line 15, in execute_dependency_jobs
    job_result_all = get_task_result(default_engine, 0)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 14, in get_task_result
    username = get_users()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 6, in get_users
    if 'username' in session:
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2023-09-06 04:17:33] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 04:17:33] [INFO] >>>  Running job "execute_sql (trigger: cron[hour='4', minute='17', second='0'], next run at: 2023-09-07 04:17:21 CST)" (scheduled at 2023-09-06 04:17:33.022828+08:00)
[2023-09-06 04:17:33] [DEBUG] >>>  Next wakeup is due at 2023-09-06 05:03:12.362279+08:00 (in 2739.296452 seconds)
[2023-09-06 04:17:37] [INFO] >>>  Ö´ĞĞÍê³É: func_ads_gp_oa_t_area_unit_sales_dd
[2023-09-06 04:17:37] [ERROR] >>>  Job "execute_sql (trigger: cron[hour='4', minute='17', second='0'], next run at: 2023-09-07 04:17:21 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\offline_task\schedule_task.py", line 317, in execute_sql
    execute_dependency_jobs(default_engine)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\dags\dags_task.py", line 15, in execute_dependency_jobs
    job_result_all = get_task_result(default_engine, 0)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 14, in get_task_result
    username = get_users()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 6, in get_users
    if 'username' in session:
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2023-09-06 05:03:12] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 05:03:12] [INFO] >>>  Running job "execute_sql (trigger: cron[hour='5', minute='3', second='0'], next run at: 2023-09-07 05:03:12 CST)" (scheduled at 2023-09-06 05:03:12.362279+08:00)
[2023-09-06 05:03:12] [DEBUG] >>>  Next wakeup is due at 2023-09-06 05:18:55.945338+08:00 (in 943.563270 seconds)
[2023-09-06 05:03:16] [INFO] >>>  Ö´ĞĞÍê³É: func_grant_select_develop_depart
[2023-09-06 05:03:16] [ERROR] >>>  Job "execute_sql (trigger: cron[hour='5', minute='3', second='0'], next run at: 2023-09-07 05:03:12 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\offline_task\schedule_task.py", line 317, in execute_sql
    execute_dependency_jobs(default_engine)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\dags\dags_task.py", line 15, in execute_dependency_jobs
    job_result_all = get_task_result(default_engine, 0)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 14, in get_task_result
    username = get_users()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 6, in get_users
    if 'username' in session:
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2023-09-06 05:18:55] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 05:18:55] [INFO] >>>  Running job "execute_sql (trigger: cron[hour='5', minute='18', second='0'], next run at: 2023-09-07 05:18:26 CST)" (scheduled at 2023-09-06 05:18:55.945338+08:00)
[2023-09-06 05:18:55] [DEBUG] >>>  Next wakeup is due at 2023-09-06 05:34:04.085567+08:00 (in 908.125730 seconds)
[2023-09-06 05:19:01] [INFO] >>>  Ö´ĞĞÍê³É: func_formmain_129544
[2023-09-06 05:19:01] [ERROR] >>>  Job "execute_sql (trigger: cron[hour='5', minute='18', second='0'], next run at: 2023-09-07 05:18:26 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\offline_task\schedule_task.py", line 317, in execute_sql
    execute_dependency_jobs(default_engine)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\dags\dags_task.py", line 15, in execute_dependency_jobs
    job_result_all = get_task_result(default_engine, 0)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 14, in get_task_result
    username = get_users()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 6, in get_users
    if 'username' in session:
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2023-09-06 05:34:04] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 05:34:04] [INFO] >>>  Running job "execute_sql (trigger: cron[hour='5', minute='34', second='0'], next run at: 2023-09-07 05:34:53 CST)" (scheduled at 2023-09-06 05:34:04.085567+08:00)
[2023-09-06 05:34:04] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 14155.900322 seconds)
[2023-09-06 05:34:04] [INFO] >>>  Ö´ĞĞÍê³É: func_ads_gp_all_t_cpx_cp_zhibiao_df
[2023-09-06 05:34:04] [ERROR] >>>  Job "execute_sql (trigger: cron[hour='5', minute='34', second='0'], next run at: 2023-09-07 05:34:53 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\offline_task\schedule_task.py", line 317, in execute_sql
    execute_dependency_jobs(default_engine)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\dags\dags_task.py", line 15, in execute_dependency_jobs
    job_result_all = get_task_result(default_engine, 0)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 14, in get_task_result
    username = get_users()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 6, in get_users
    if 'username' in session:
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2023-09-06 09:04:53] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:53] "GET /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:04:53] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:53] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:04:53] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:53] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:04:53] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:53] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "GET /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "GET /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "GET /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:04:54] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:54] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:04:55] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:55] "GET /operation/html/dags/job1 HTTP/1.1" 200 -
[2023-09-06 09:04:55] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:55] "[33mGET /operation/static/css/styles_upsl.css HTTP/1.1[0m" 404 -
[2023-09-06 09:04:59] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:04:59] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1500.864518 seconds)
[2023-09-06 09:04:59] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:04:59] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1500.859513 seconds)
[2023-09-06 09:04:59] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:04:59] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1500.855518 seconds)
[2023-09-06 09:04:59] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:04:59] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1500.850516 seconds)
[2023-09-06 09:04:59] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:04:59] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1500.846516 seconds)
[2023-09-06 09:04:59] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:59] "GET /offline_task/html/schedule_task HTTP/1.1" 200 -
[2023-09-06 09:04:59] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:59] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:04:59] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:59] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:04:59] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:59] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:04:59] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:59] "[36mGET /static/js/edit_nodes.js HTTP/1.1[0m" 304 -
[2023-09-06 09:04:59] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:59] "[36mGET /static/js/option_get_json.js HTTP/1.1[0m" 304 -
[2023-09-06 09:04:59] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:04:59] "[36mGET /static/config.json HTTP/1.1[0m" 304 -
[2023-09-06 09:05:02] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:02] "GET /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:05:02] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:02] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:05:02] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:02] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:05:02] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:02] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:05:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:05] "POST /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:05:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:05] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:05:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:05] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:05:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:05] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:05:07] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:07] "GET /operation/html/dags/job1 HTTP/1.1" 200 -
[2023-09-06 09:05:07] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:07] "[33mGET /operation/static/css/styles_upsl.css HTTP/1.1[0m" 404 -
[2023-09-06 09:05:22] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:22] "POST /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:05:23] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:23] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:05:23] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:23] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:05:23] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:23] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:05:25] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:25] "GET /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:05:25] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:25] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:05:25] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:25] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:05:25] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:25] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:05:28] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:28] "GET /operation/html/dags/func_grant_select_develop_depart HTTP/1.1" 200 -
[2023-09-06 09:05:28] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:28] "[33mGET /operation/static/css/styles_upsl.css HTTP/1.1[0m" 404 -
[2023-09-06 09:05:36] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:36] "POST /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:05:36] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:36] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:05:36] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:36] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:05:36] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:36] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:05:41] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:41] "POST /operation/html/operation HTTP/1.1" 200 -
[2023-09-06 09:05:41] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:41] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:05:41] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:41] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:05:41] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:41] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:05:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:57] "GET /operation/html/overview HTTP/1.1" 200 -
[2023-09-06 09:05:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:57] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:05:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:05:57] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:06:03] [ERROR] >>>  Exception on /property [GET]
Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\connections.py", line 756, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] ÄãµÄÖ÷»úÖĞµÄÈí¼şÖĞÖ¹ÁËÒ»¸öÒÑ½¨Á¢µÄÁ¬½Ó¡£

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\connections.py", line 759, in _write_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'ÄãµÄÖ÷»úÖĞµÄÈí¼şÖĞÖ¹ÁËÒ»¸öÒÑ½¨Á¢µÄÁ¬½Ó¡£', None, 10053, None))")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\app.py", line 128, in show_table_info
    return property.show_property()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\property.py", line 10, in show_property
    table_names = show_table_names()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\property.py", line 24, in show_table_names
    result = default_engine.execute(query)
  File "<string>", line 2, in execute
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\util\deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 3176, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1291, in execute
    return self._exec_driver_sql(
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1595, in _exec_driver_sql
    ret = self._execute_context(
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\pymysql\connections.py", line 759, in _write_bytes
    raise err.OperationalError(
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'ÄãµÄÖ÷»úÖĞµÄÈí¼şÖĞÖ¹ÁËÒ»¸öÒÑ½¨Á¢µÄÁ¬½Ó¡£', None, 10053, None))")
[SQL: 
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'job_task'
    LIMIT 500
    ]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-09-06 09:06:03] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:03] "[33mGET /property HTTP/1.1[0m" 404 -
[2023-09-06 09:06:03] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:03] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:06:03] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:03] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:06:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:05] "GET /property HTTP/1.1" 200 -
[2023-09-06 09:06:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:05] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:06:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:05] "[36mGET /static/js/pagination.js HTTP/1.1[0m" 304 -
[2023-09-06 09:06:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:05] "[36mGET /static/js/diag.js HTTP/1.1[0m" 304 -
[2023-09-06 09:06:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:05] "[36mGET /static/js/d3.min.js HTTP/1.1[0m" 304 -
[2023-09-06 09:06:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:05] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:06:05] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:05] "[36mGET /static/js/dagre-d3.js HTTP/1.1[0m" 304 -
[2023-09-06 09:06:07] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:07] "GET /property/tem_test1111 HTTP/1.1" 200 -
[2023-09-06 09:06:07] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:07] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:06:07] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:07] "[36mGET /static/js/pagination.js HTTP/1.1[0m" 304 -
[2023-09-06 09:06:07] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:07] "[36mGET /static/js/d3.min.js HTTP/1.1[0m" 304 -
[2023-09-06 09:06:07] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:07] "[36mGET /static/js/dagre-d3.js HTTP/1.1[0m" 304 -
[2023-09-06 09:06:07] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:07] "[36mGET /static/js/diag.js HTTP/1.1[0m" 304 -
[2023-09-06 09:06:07] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:06:07] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:07:37] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:07:37] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1342.563143 seconds)
[2023-09-06 09:07:37] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:07:37] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1342.557139 seconds)
[2023-09-06 09:07:37] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:07:37] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1342.553126 seconds)
[2023-09-06 09:07:37] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:07:37] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1342.549144 seconds)
[2023-09-06 09:07:37] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:07:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:07:37] "GET /offline_task/html/data_sync HTTP/1.1" 200 -
[2023-09-06 09:07:37] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 1342.543133 seconds)
[2023-09-06 09:07:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:07:37] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:07:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:07:37] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:07:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:07:37] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:07:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:07:37] "[36mGET /static/js/option_get_json.js HTTP/1.1[0m" 304 -
[2023-09-06 09:07:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:07:37] "[36mGET /static/js/edit_nodes.js HTTP/1.1[0m" 304 -
[2023-09-06 09:07:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:07:37] "[36mGET /static/config.json HTTP/1.1[0m" 304 -
[2023-09-06 09:24:35] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:24:35] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 324.631455 seconds)
[2023-09-06 09:24:35] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:24:35] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 324.627453 seconds)
[2023-09-06 09:24:35] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:24:35] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 324.622457 seconds)
[2023-09-06 09:24:35] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:24:35] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 324.618454 seconds)
[2023-09-06 09:24:35] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:24:35] [DEBUG] >>>  Next wakeup is due at 2023-09-06 09:30:00+08:00 (in 324.613457 seconds)
[2023-09-06 09:24:35] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:24:35] "GET /offline_task/html/schedule_task HTTP/1.1" 200 -
[2023-09-06 09:24:35] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:24:35] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:24:35] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:24:35] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 09:24:35] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:24:35] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:24:35] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:24:35] "[36mGET /static/js/option_get_json.js HTTP/1.1[0m" 304 -
[2023-09-06 09:24:35] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:24:35] "[36mGET /static/js/edit_nodes.js HTTP/1.1[0m" 304 -
[2023-09-06 09:24:35] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:24:35] "[36mGET /static/config.json HTTP/1.1[0m" 304 -
[2023-09-06 09:29:55] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:55] "GET /property HTTP/1.1" 200 -
[2023-09-06 09:29:55] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:55] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:29:55] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:55] "[36mGET /static/js/d3.min.js HTTP/1.1[0m" 304 -
[2023-09-06 09:29:55] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:55] "[36mGET /static/js/pagination.js HTTP/1.1[0m" 304 -
[2023-09-06 09:29:55] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:55] "[36mGET /static/js/diag.js HTTP/1.1[0m" 304 -
[2023-09-06 09:29:55] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:55] "[36mGET /static/js/dagre-d3.js HTTP/1.1[0m" 304 -
[2023-09-06 09:29:55] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:55] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:29:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:57] "GET /property/test_105321 HTTP/1.1" 200 -
[2023-09-06 09:29:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:57] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:29:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:57] "[36mGET /static/js/pagination.js HTTP/1.1[0m" 304 -
[2023-09-06 09:29:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:57] "[36mGET /static/js/d3.min.js HTTP/1.1[0m" 304 -
[2023-09-06 09:29:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:57] "[36mGET /static/js/dagre-d3.js HTTP/1.1[0m" 304 -
[2023-09-06 09:29:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:57] "[36mGET /static/js/diag.js HTTP/1.1[0m" 304 -
[2023-09-06 09:29:57] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:29:57] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:30:00] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 09:30:00] [INFO] >>>  Running job "execute_sql (trigger: cron[hour='9', minute='30', second='0'], next run at: 2023-09-07 09:30:00 CST)" (scheduled at 2023-09-06 09:30:00+08:00)
[2023-09-06 09:30:00] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 18971.969951 seconds)
[2023-09-06 09:32:03] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:32:03] "GET /pro_management/html/add_users HTTP/1.1" 200 -
[2023-09-06 09:32:03] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:32:03] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:32:03] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:32:03] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:32:03] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:32:03] "[36mGET /static/js/edit_nodes.js HTTP/1.1[0m" 304 -
[2023-09-06 09:32:40] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:32:40] "GET /pro_management/html/data_source HTTP/1.1" 200 -
[2023-09-06 09:32:40] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:32:40] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 09:32:40] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 09:32:40] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 09:45:00] [INFO] >>>  SQLÖ´ĞĞ³É¹¦: func_ods_2156_shangji_detail
[2023-09-06 09:45:00] [ERROR] >>>  Job "execute_sql (trigger: cron[hour='9', minute='30', second='0'], next run at: 2023-09-07 09:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\offline_task\data_sync.py", line 426, in execute_sql
    execute_dependency_jobs(default_engine)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\dags\dags_task.py", line 15, in execute_dependency_jobs
    job_result_all = get_task_result(default_engine, 0)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 14, in get_task_result
    username = get_users()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 6, in get_users
    if 'username' in session:
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2023-09-06 10:28:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 10:28:48] "GET /pro_management/html/add_users HTTP/1.1" 200 -
[2023-09-06 10:28:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 10:28:48] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 10:28:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 10:28:48] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 10:28:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 10:28:48] "[36mGET /static/js/edit_nodes.js HTTP/1.1[0m" 304 -
[2023-09-06 11:29:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:37] "[32mGET / HTTP/1.1[0m" 302 -
[2023-09-06 11:29:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:37] "GET /users/html/users_login HTTP/1.1" 200 -
[2023-09-06 11:29:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:37] "[32mGET /static/dataflow.ico HTTP/1.1[0m" 302 -
[2023-09-06 11:29:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:37] "GET /users/html/users_login HTTP/1.1" 200 -
[2023-09-06 11:29:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:37] "[32mGET /favicon.ico HTTP/1.1[0m" 302 -
[2023-09-06 11:29:37] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:37] "GET /users/html/users_login HTTP/1.1" 200 -
[2023-09-06 11:29:40] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:40] "[32mPOST /users/html/users_login HTTP/1.1[0m" 302 -
[2023-09-06 11:29:40] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:40] "GET / HTTP/1.1" 200 -
[2023-09-06 11:29:40] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:40] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 11:29:40] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:40] "GET /static/dataflow.ico HTTP/1.1" 200 -
[2023-09-06 11:29:40] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:40] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2023-09-06 11:29:48] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 11:29:48] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 11783.561352 seconds)
[2023-09-06 11:29:48] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 11:29:48] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 11783.556346 seconds)
[2023-09-06 11:29:48] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 11:29:48] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 11783.551340 seconds)
[2023-09-06 11:29:48] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 11:29:48] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 11783.547348 seconds)
[2023-09-06 11:29:48] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 11:29:48] [INFO] >>>  Running job "execute_sql (trigger: cron[hour='9', minute='36', second='0'], next run at: 2023-09-07 09:36:32 CST)" (scheduled at 2023-09-06 11:29:48.438931+08:00)
[2023-09-06 11:29:48] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 11783.538351 seconds)
[2023-09-06 11:29:48] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 11:29:48] [INFO] >>>  Ö´ĞĞÍê³É: job6
[2023-09-06 11:29:48] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 11783.525351 seconds)
[2023-09-06 11:29:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:48] "GET /offline_task/html/schedule_task HTTP/1.1" 200 -
[2023-09-06 11:29:48] [ERROR] >>>  Job "execute_sql (trigger: cron[hour='9', minute='36', second='0'], next run at: 2023-09-07 09:36:32 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\offline_task\schedule_task.py", line 317, in execute_sql
    execute_dependency_jobs(default_engine)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\dags\dags_task.py", line 15, in execute_dependency_jobs
    job_result_all = get_task_result(default_engine, 0)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 14, in get_task_result
    username = get_users()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 6, in get_users
    if 'username' in session:
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2023-09-06 11:29:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:48] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 11:29:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:48] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 11:29:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:48] "[36mGET /static/js/option_get_json.js HTTP/1.1[0m" 304 -
[2023-09-06 11:29:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:48] "[36mGET /static/js/edit_nodes.js HTTP/1.1[0m" 304 -
[2023-09-06 11:29:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:48] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 11:29:48] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 11:29:48] "[36mGET /static/config.json HTTP/1.1[0m" 304 -
[2023-09-06 02:33:15] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 02:33:15] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 776.143676 seconds)
[2023-09-06 02:33:15] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 02:33:15] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 776.138678 seconds)
[2023-09-06 02:33:15] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 02:33:15] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 776.133674 seconds)
[2023-09-06 02:33:15] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 02:33:15] [DEBUG] >>>  Next wakeup is due at 2023-09-06 14:46:11.978279+08:00 (in 776.128674 seconds)
[2023-09-06 02:33:15] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 14:33:15] "GET /offline_task/html/data_sync HTTP/1.1" 200 -
[2023-09-06 02:33:15] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 14:33:15] "[36mGET /static/css/styles_upsl.css HTTP/1.1[0m" 304 -
[2023-09-06 02:33:15] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 14:33:15] "[36mGET /static/js/search_more.js HTTP/1.1[0m" 304 -
[2023-09-06 02:33:15] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 14:33:15] "[36mGET /static/js/option_get_json.js HTTP/1.1[0m" 304 -
[2023-09-06 02:33:15] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 14:33:15] "[36mGET /static/config.json HTTP/1.1[0m" 304 -
[2023-09-06 02:33:15] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 14:33:15] "[36mGET /static/dataflow.ico HTTP/1.1[0m" 304 -
[2023-09-06 02:33:15] [INFO] >>>  10.60.4.29 - - [06/Sep/2023 14:33:15] "[36mGET /static/js/edit_nodes.js HTTP/1.1[0m" 304 -
[2023-09-06 02:46:11] [DEBUG] >>>  Looking for jobs to run
[2023-09-06 02:46:11] [INFO] >>>  Running job "execute_sql (trigger: cron[hour='14', minute='46', second='0'], next run at: 2023-09-07 14:46:03 CST)" (scheduled at 2023-09-06 14:46:11.978279+08:00)
[2023-09-06 02:46:11] [DEBUG] >>>  Next wakeup is due at 2023-09-07 02:40:00.078386+08:00 (in 42828.094592 seconds)
[2023-09-06 02:46:12] [ERROR] >>>  (psycopg2.errors.SyntaxError) syntax error at or near "selfect"
LINE 1: selfect fafdsaf
        ^

[SQL: selfect fafdsaf]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-09-06 02:46:12] [ERROR] >>>  Job "execute_sql (trigger: cron[hour='14', minute='46', second='0'], next run at: 2023-09-07 14:46:03 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\offline_task\schedule_task.py", line 317, in execute_sql
    execute_dependency_jobs(default_engine)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\dags\dags_task.py", line 15, in execute_dependency_jobs
    job_result_all = get_task_result(default_engine, 0)
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 14, in get_task_result
    username = get_users()
  File "C:\Users\allan.yin\PycharmProjects\pythonProject\ah\website\templates\data_work\get_task_info.py", line 6, in get_users
    if 'username' in session:
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "C:\Users\allan.yin\Anaconda3\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
